services:
  - type: web
    name: tp-leads-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: WEB_CONCURRENCY
        value: "1"
      - key: PORT
        value: "10000"
